mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('projects.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/projects/urls.py
from django.urls import  path
from . import views

app_name = "project"

urlpatterns = [
    path('', views.index, name = 'home'),
    path('project/', views.project, name = 'proj'),
    path('task/', views.task, name = 'alltask'),
    path('project/<uuid:project_id>/', views.curentproject, name = 'curproj'),
    path('task/<int:task_id>/', views.curenttask, name='curtask'),
    path('task/<int:task_id>/change/', views.changetask, name='changecurtask'),

]

mysite/projects/models.py
from django.db import models
import uuid
from tinymce.models import HTMLField
from django.contrib.auth.models import User


# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='images/users', verbose_name='Изображение')

    def __unicode__(self):
        return self.user

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Project(models.Model):
    project_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project_name = models.CharField('имя проекта', max_length=200)
    project_description = HTMLField('описание проекта')
    project_members = models.ManyToManyField(User, related_name= 'members', blank =True, verbose_name='Участники')
    def __str__(self):
        return self.project_name

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class Task(models.Model):
    task_id = models.IntegerField
    task_theme = models.CharField('тема задания', max_length=200)
    task_description = models.TextField('описание задания')
    task_datestart = models.DateTimeField('начало задания')
    task_dateend = models.DateTimeField('окончания задания')

    t_type = (
        ('Фича', 'Фича'),
        ('Баг', 'Баг'),
    )
    task_type = models.CharField('тип задания', max_length=30, choices=t_type)

    t_priority = (
        ('Нормальный', 'Нормальный'),
        ('Высокий', 'Высокий'),
        ('Срочный', 'Срочный'),
    )
    task_priority = models.CharField('приоритет задания', max_length=30, choices=t_priority)
    task_spenttime = models.IntegerField('время на задание(в часах)')
    task_executor = models.ForeignKey('auth.User', verbose_name='исполнитель', on_delete=models.CASCADE, related_name='task_executor')
    task_author = models.ForeignKey('auth.User', verbose_name='автор', on_delete=models.CASCADE, related_name='task_author', editable=True )
    task_project = models.ForeignKey(Project, verbose_name='проект', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.task_theme

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class NewComment(models.Model):
    comment_id = models.IntegerField
    comment_author = models.ForeignKey('auth.User', verbose_name='автор', on_delete=models.CASCADE, related_name='comment_author' )
    comment_description = models.TextField('Текст комментария', max_length= 200)
    comment_date = models.DateTimeField('Дата комментария' , auto_now_add=True)
    comment_task = models.ForeignKey(Task, verbose_name='Имя задачи №', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.comment_description

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

mysite/projects/forms.py
from django import forms
from .models import Task, NewComment

class ChangeTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        exclude = ['task_author', 'task_project']

class AddComment(forms.ModelForm):

    class Meta:
        model = NewComment
        fields = ['comment_description']

mysite/projects/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Project, Task, NewComment

from .forms import ChangeTaskForm, AddComment
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required




def index(request):
    return render(request, 'projects/index.html')

@login_required
def project(request):
    if request.user.groups.filter(name = 'perms_user').exists():
        proj = Project.objects.filter(project_members = request.user)
        return render(request, 'projects/projects.html', {'title': 'Ваши проекты', 'proj': proj})


@login_required
def task(request):
    if request.user.groups.filter(name = 'perms_user').exists():
        task = Task.objects.filter(task_executor= request.user)
        return  render(request, 'projects/task.html', {'title': 'Ваши задачи', 'task': task})
    else:
        return HttpResponse("Что-то пошло не так!")


@login_required
def curentproject( request,  project_id ):
    curproj = Project.objects.get(pk = project_id)
    return render(request, 'projects/curproject.html', {'title': 'Ваши проекты','curproj': curproj})


@login_required
def curenttask(request, task_id):
    curtask = get_object_or_404(Task, id = task_id)
    comment = NewComment.objects.filter(comment_task=curtask).order_by('-comment_date')[:5]
    if request.method == "POST":
        form = AddComment(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.comment_author = request.user
            comm.comment_task = curtask
            comm.save()
    else:
        form = AddComment()
    return render(request, 'projects/curtask.html', {'title': 'Ваши задачи','curtask': curtask, 'form':form, 'comment':comment})


@login_required
def changetask(request, task_id ):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST":
        form = ChangeTaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            task.save()
        return redirect("project:alltask")
    else:
        form = ChangeTaskForm(instance=task)
    return render(request, 'projects/changetask_form.html', {'title': 'Отредактируйте поля', 'form2': form})

mysite/projects/templates/projects/base.html
<!doctype html>
{% load static %}
<html lang=ru>
<head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %}{% endblock %} </title>
     <link rel= "canonical" href= "https://getbootstrap.com/docs/5.1/examples/album/">
    <link rel = "stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous",
    src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
    </script>

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<meta name="theme-color" content="#7952b3">

</head>
<body>
<header>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'project:home' %}">Welcome</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%url 'project:home' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'project:proj' %}">Проекты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{%url 'project:alltask' %}">Задачи</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-link"> Пользователь: {{ user.get_username }}</li>
                {% if user.userprofile.avatar %}
                <img class = "uimg" src="{{ user.userprofile.avatar.url }}"/>
                {% else %}
                <img class = "uimg" src="{% static 'images/anon.jpg' %}"/>
                {% endif %}
        <li><a  class="nav-link " href="{% url 'logout'%}">Logout</a></li>
        {% else %}
         <li><a class="nav-link" href="{% url 'login'%}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
</header>

<div class= "container">
    {% block content %}
    {% endblock %}
</div>

<footer class="footer " >
        <div class="footer-copyright text-center py-3">© 2022 Copyright:
    <a href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
</footer>

</body>
</html>

mysite/projects/templates/projects/changetask_form.html
{% extends 'projects/base.html' %}
{% block title %}
{{ title }}
{% endblock %}


{% block content %}
<h1>Редактируйте поля</h1>

<div class = "alert alert-info mt-2">

    <form  method="post">
            {% csrf_token %}
       <table>
            {{ form2.as_table }}
       </table><br>
            <input type="submit" value="Отправить" />
            </form>
</div>

{% endblock %}

mysite/projects/templates/projects/curproject.html
{% extends 'projects/base.html' %}
{% block title %}
{{ title }}
{% endblock %}


{% block content %}
<h1>Ваши  проекты</h1>

        <div class = "alert alert-info mt-2">
            <h2>Название проекта: {{curproj.project_name}}</h2>
             Описание проекта: {{curproj.project_description|safe}}
        </div>

{% endblock %}

mysite/projects/templates/projects/curtask.html
{% extends 'projects/base.html' %}
{% block title %}
{{ title }}
{% endblock %}
{% load static %}

{% block content %}
<h1>Ваши  задачи</h1>

        <div class = "alert alert-info mt-2">
            <h2>Проект: {{curtask.task_project}}</h2>
             <p>Тема задания: {{curtask.task_theme}}</p>
             <p>Описание задания: {{curtask.task_description}}</p>
             <p>Тип задания: {{curtask.task_type}}</p>
             <p>Приоритет задания: {{curtask.task_priority}}</p>
             <p>Время на задание(в часах): {{curtask.task_spenttime}}</p>
             <p>Дата начала задания: {{curtask.task_datestart}} </p>
             <p>Дата окончания задания: {{curtask.task_dateend}} </p>
             <p>Автор: {{curtask.task_author}}</p>
             <p>Исполнитель: {{curtask.task_executor}}</p>
        </div>

<form action="{%url 'project:changecurtask'  curtask.id %}" >
  <button id ="but" ><img class="editimg" src="{% static 'images/edit.png' %}" ></button>
</form>

<div class = "alert alert-secondary mt-2">

            <h3>Список комментариев: </h3>
        {%for com in comment%}
             <p>Автор: {{ com.comment_author }}</p>
             <p>Текст комментария: {{com.comment_description}}</p>
             <p>Дата комментария: {{com.comment_date}}</p>
             <br>
        {%endfor%}

</div>

<form  method="post">
            {% csrf_token %}
       <table>
            {{ form }}
       </table><br>
            <input type="submit" value="Отправить" />
</form><br>
{% endblock %}

mysite/projects/templates/projects/index.html
{% extends 'projects/base.html' %}
{% block title %}
Главная страница
{% endblock %}

{% block content %}
{% load static %}
     <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Nice to meet {{ user.get_username }}!</h1>

            <img class="gimg" src="{% static 'images/welcome.jpg' %}" />
      </div>
    </div>
  </section>
{% endblock %}

mysite/projects/templates/projects/projects.html
{% extends 'projects/base.html' %}
{% block title %}
{{ title }}
{% endblock %}


{% block content %}
    <h1>Список ваших проектов</h1>
    {% for p in proj %}
        <div class = "alert alert-info mt-2">
            <h4> Название проекта: <a href ="{% url 'project:curproj' p.pk %}">{{p.project_name}}</a></h4>
            Описание проекта:{{p.project_description|safe}}
        </div>
    {% endfor %}



{% endblock %}

mysite/projects/templates/projects/task.html
{% extends 'projects/base.html' %}
{% block title %}
{{title}}
{% endblock %}


{% block content %}
    <h1>Задачи</h1>

    {% for t in task %}
        <div class = "alert alert-info mt-2">
             <h3>Проект: {{t.task_project}}</a></h3>
             <p>Тема задания: <a href ="{% url 'project:curtask' t.id %}">{{t.task_theme}}</a></p>
             <p>Описание задания: {{t.task_description}}</p>
             <p>Автор: {{t.task_author}}</p>
             <p>Исполнитель: {{t.task_executor}}</p>
        </div>
    {% endfor %}

{% endblock %}